version: "3.9"
services:
  express: 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:${PORT}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U${POSTGRES_USER}", "-d${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
  admin:
    image: dpage/pgadmin4:latest
    ports:
      - 5555:80
    env_file:
      - .env